export const categories = [
  { id: "venues", name: "Venues", short: "Spaces with soul", icon: "Landmark" },
  { id: "photography", name: "Photography", short: "Stories, not poses", icon: "Camera" },
  { id: "decor", name: "Decor & florals", short: "Your world, made real", icon: "Flower2" },
  { id: "catering", name: "Catering", short: "Menus worth gathering for", icon: "UtensilsCrossed" },
  { id: "beauty", name: "Bridal beauty", short: "Feel most like yourself", icon: "Sparkles" },
  { id: "music", name: "Music & entertainment", short: "Keep every floor full", icon: "Music2" },
];

export const cities = ["Delhi NCR", "Mumbai", "Jaipur", "Bengaluru", "Goa", "Udaipur", "Hyderabad", "Kolkata"];

export const vendors = [
  {
    id: "haveli-noor",
    name: "Haveli Noor",
    category: "venues",
    categoryLabel: "Heritage venue",
    city: "Jaipur",
    price: 650000,
    priceLabel: "from ₹6.5L",
    rating: 4.9,
    reviews: 86,
    response: "Replies in 2 hrs",
    verified: true,
    tags: ["180–450 guests", "Rooms included", "Rain plan"],
    tone: "marigold",
    initials: "HN",
    availability: "3 dates left this season",
  },
  {
    id: "the-wedding-journal",
    name: "The Wedding Journal",
    category: "photography",
    categoryLabel: "Photo + film",
    city: "Delhi NCR",
    price: 185000,
    priceLabel: "from ₹1.85L",
    rating: 4.8,
    reviews: 124,
    response: "Replies in 45 min",
    verified: true,
    tags: ["Candid", "Film edit", "Drone"],
    tone: "rose",
    initials: "WJ",
    availability: "Available for your dates",
  },
  {
    id: "mogra-studio",
    name: "Mogra Studio",
    category: "decor",
    categoryLabel: "Decor & florals",
    city: "Mumbai",
    price: 425000,
    priceLabel: "from ₹4.25L",
    rating: 4.9,
    reviews: 63,
    response: "Replies in 3 hrs",
    verified: true,
    tags: ["Fresh florals", "Custom builds", "Lighting"],
    tone: "teal",
    initials: "MS",
    availability: "2 consultation slots this week",
  },
  {
    id: "saffron-table",
    name: "Saffron Table Co.",
    category: "catering",
    categoryLabel: "Catering",
    city: "Bengaluru",
    price: 2100,
    priceLabel: "from ₹2,100 / plate",
    rating: 4.7,
    reviews: 97,
    response: "Replies in 90 min",
    verified: true,
    tags: ["Regional menus", "Live counters", "Tasting"],
    tone: "aubergine",
    initials: "ST",
    availability: "Tastings open this month",
  },
  {
    id: "house-of-aabha",
    name: "House of Aabha",
    category: "beauty",
    categoryLabel: "Bridal beauty",
    city: "Delhi NCR",
    price: 48000,
    priceLabel: "from ₹48K",
    rating: 4.9,
    reviews: 152,
    response: "Replies in 1 hr",
    verified: true,
    tags: ["HD makeup", "Hair", "Trial included"],
    tone: "rose",
    initials: "HA",
    availability: "Available for your dates",
  },
  {
    id: "sur-taal-collective",
    name: "Sur Taal Collective",
    category: "music",
    categoryLabel: "Live entertainment",
    city: "Goa",
    price: 135000,
    priceLabel: "from ₹1.35L",
    rating: 4.8,
    reviews: 71,
    response: "Replies in 4 hrs",
    verified: true,
    tags: ["Sufi set", "DJ", "Sound setup"],
    tone: "teal",
    initials: "ST",
    availability: "Weekend holds available",
  },
  {
    id: "lakehouse-udai",
    name: "Lakehouse Udai",
    category: "venues",
    categoryLabel: "Destination venue",
    city: "Udaipur",
    price: 1250000,
    priceLabel: "from ₹12.5L",
    rating: 4.8,
    reviews: 49,
    response: "Replies in 5 hrs",
    verified: true,
    tags: ["120 rooms", "Lake view", "Buyout"],
    tone: "aubergine",
    initials: "LU",
    availability: "Winter 2027 dates open",
  },
  {
    id: "petal-and-plume",
    name: "Petal & Plume",
    category: "decor",
    categoryLabel: "Sustainable decor",
    city: "Goa",
    price: 310000,
    priceLabel: "from ₹3.1L",
    rating: 4.6,
    reviews: 42,
    response: "Replies tomorrow",
    verified: false,
    tags: ["Foam-free", "Local florals", "Rentals"],
    tone: "marigold",
    initials: "PP",
    availability: "Consultations available",
  },
];

export const sampleOffers = [
  {
    vendor: "Haveli Noor",
    total: "₹7.10L",
    delta: "Best value",
    inclusions: 8,
    fit: 94,
    highlight: "Rooms + backup lawn",
  },
  {
    vendor: "Baradari House",
    total: "₹7.85L",
    delta: "₹75K more",
    inclusions: 7,
    fit: 89,
    highlight: "Late-night permit",
  },
  {
    vendor: "Kesar Courtyard",
    total: "₹6.90L",
    delta: "Lowest price",
    inclusions: 5,
    fit: 82,
    highlight: "Decor not included",
  },
];

export const dashboardTasks = [
  { id: 1, title: "Shortlist venue offers", meta: "3 offers close Friday", priority: "Now", done: false },
  { id: 2, title: "Confirm guest count range", meta: "Needed for catering brief", priority: "This week", done: false },
  { id: 3, title: "Share decor moodboard", meta: "Mogra Studio is waiting", priority: "This week", done: false },
  { id: 4, title: "Book photography consultation", meta: "Completed 14 Aug", priority: "Done", done: true },
];

export const opportunities = [
  {
    id: "MLV-2841",
    service: "Photography + film",
    city: "Delhi NCR",
    date: "18 Feb 2027",
    guests: 320,
    budget: "₹1.8L–₹2.4L",
    closes: "Closes in 18 hours",
    match: 96,
    notes: "Two-day celebration; candid storytelling and same-day edit preferred.",
  },
  {
    id: "MLV-2838",
    service: "Mehendi decor",
    city: "Jaipur",
    date: "9 Dec 2026",
    guests: 140,
    budget: "₹1.2L–₹1.8L",
    closes: "Closes tomorrow",
    match: 91,
    notes: "Daytime courtyard event with marigold-led, low-waste decor.",
  },
  {
    id: "MLV-2829",
    service: "Live band + DJ",
    city: "Goa",
    date: "21 Jan 2027",
    guests: 210,
    budget: "₹1.1L–₹1.6L",
    closes: "Closes in 2 days",
    match: 87,
    notes: "Sunset set into a high-energy dance floor; sound production required.",
  },
];

export function formatCurrency(value) {
  if (!Number.isFinite(Number(value))) return "₹0";
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(Number(value));
}
